timeout 1
default Buildroot
menu title boot prev kernel

label Buildroot
	kernel /boot/Image
	fdt /boot/sdm632-fairphone-fp3.dtb
	append earlycon console=ttyMSM0,115200 fbcon=rotate:1 fbcon=font:TER16x32 root=/dev/mmcblk0p62 rootfstype=ext3 quiet rw rootwait
